name: pr test
on:
  pull_request:

jobs:
  auto-build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            target: aarch64-linux-android

    name: 🛠️ 自动构建
    runs-on: ${{ matrix.os }}
    steps:
      - name: 克隆当前仓库 (Clone current repo)
        uses: actions/checkout@v5
