name: ssh

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-22.04
    steps:
      - name: 克隆当前仓库 (Clone current repo)
        uses: actions/checkout@v4

      - name: 开启 SSH 服务 (Start SSH service)
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 15
