name: Upload Two Text Files

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/upload-artifact@v7
        with:
          name: abc
          archive: false
          path: ./result/xyz/abc.txt

      - uses: actions/upload-artifact@v7
        with:
          name: abc2
          archive: false
          path: ./result/xyz/abc2.txt
